export const SEARCH_REPO_ACTION = 'SEARCH_REPO_ACTION';
export const SEARCH_REPO_SUCCESS_ACTION = 'SEARCH_REPO_SUCCESS_ACTION';
export const FETCH_BOOKMARKED_REPO_ACTION = 'FETCH_BOOKMARKED_REPO_ACTION';
export const FETCH_BOOKMARKED_REPO_SUCCESS_ACTION =
  'FETCH_BOOKMARKED_REPO_SUCCESS_ACTION';
export const FETCH_BOOKMARKED_REPO_FAIL_ACTION =
  'FETCH_BOOKMARKED_REPO_FAIL_ACTION';
