export const CREATE_ISSUE_ACTION = 'CREATE_ISSUE_ACTION';
export const CREATE_ISSUE_SUCCESS_ACTION = 'CREATE_ISSUE_SUCCESS_ACTION';
export const CREATE_ISSUE_FAIL_ACTION = 'CREATE_ISSUE_FAIL_ACTION';
export const CREATE_ISSUE_CLEAR_ACTION = 'CREATE_ISSUE_CLEAR_ACTION';
