export const FETCH_REPO_ISSUES_ACTION = 'FETCH_REPO_ISSUES_ACTION';
export const FETCH_REPO_ISSUES_SUCCESS_ACTION =
  'FETCH_REPO_ISSUES_SUCCESS_ACTION';
export const BOOKMARK_REPO_ACTION = 'BOOKMARK_REPO_ACTION';
export const BOOKMARK_REPO_SUCCESS_ACTION = 'BOOKMARK_REPO_SUCCESS_ACTION';
export const CHECK_USER_BOOKMARK_ACTION = 'CHECK_USER_BOOKMARK_ACTION';
export const CHECK_USER_BOOKMARK_SUCCESS_ACTION =
  'CHECK_USER_BOOKMARK_SUCCESS_ACTIONON';
