export const FETCH_REPO_ISSUES_ACTION = 'FETCH_REPO_ISSUES_ACTION';
export const FETCH_REPO_ISSUES_SUCCESS_ACTION =
  'FETCH_REPO_ISSUES_SUCCESS_ACTION';
export const BOOKMARK_REPO_ACTION = 'BOOKMARK_REPO_ACTION';
export const BOOKMARK_REPO_SUCCESS_ACTION = 'BOOKMARK_REPO_SUCCESS_ACTION';
