export const LOGIN_ACTION = 'LOGIN_ACTION';
export const LOGIN_ACTION_SUCCESS = 'LOGIN_ACTION_SUCCESS';
export const LOGIN_ACTION_FAIL = 'LOGIN_ACTION_FAIL';
export const REGISTER_ACTION = 'REGISTER_ACTION';
export const REGISTER_SUCCESS_ACTION = 'REGISTER_SUCCESS_ACTION';
export const REGISTER_FAIL_ACTION = 'REGISTER_FAIL_ACTION';
