export const LOGIN_ACTION = 'LOGIN_ACTION';
export const LOGIN_ACTION_SUCCESS = 'LOGIN_ACTION_SUCCESS';
export const REGISTER_ACTION = 'REGISTER_ACTION';
export const REGISTER_ACTION_SUCCESS = 'REGISTER_ACTION_SUCCESS';
